### ISSUE TITLE
I trying to patch appointment but it's always return error

### ISSUE THREAD

**Issue by thuann-vn** [smart-on-fhir/client-js#129] opened 2021-06-09 04:51 UTC
Please help me if I did it wrong. Thank you

Notes: I also tried JSON.stringify and without JSON.stringify but still the same.

**Request:**
```
client.request({
    url: "Appointment/1335690",
    method: "PATCH",
    headers:{
        'Content-Type': 'application/json-patch+json'
    },
    body: JSON.stringify([
        {
            "op": "replace",
            "path": "/status",
            "value": "cancelled"
          }
      ])
})
```

**Response:**
```
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.NullPointerException: input cannot be null"
    }
  ]
}
```

**Comment by vlad-ignatov** [comment] 2021-06-09 11:28
Try this:
```js
client.request({
    url: "Appointment/1335690",
    method: "PATCH",
    body: {
        "op": "replace",
        "path": "/status",
        "value": "cancelled"
    }
})
```

**Comment by thuann-vn** [comment] 2021-06-10 01:56
hi @vlad-ignatov, I don't know why, but it still returning 500 Internal Server error
URL: https://launch.smarthealthit.org/v/r4/fhir/Appointment/1335733

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: java.lang.NullPointerException: input cannot be null"
        }
    ]
}
```

**Comment by vlad-ignatov** [comment] 2021-06-10 15:18
I didn't pay enough attention to this one initially, but now that I did, I can say it is more complicated.
1. I gave you wrong example. Your first attempt was fine.
2. The problem is on the server side. It should work against https://r4.smarthealthit.org but it does not work against https://launch.smarthealthit.org/v/r4/fhir/. The reason is that the latter is just a proxy in front of https://r4.smarthealthit.org, and apparently it does not handle PATCH requests properly. That is also for me to fix ASAP, but it is another project's issue...
3. I figured doing PATCH requests can be tricky and people could use some help and input validation. I've added new dedicated `patch` method to the client now - c4c8408. This should be released shortly.

**Comment by vlad-ignatov** [comment] 2021-06-10 17:57
Now released in v2.4.0. Please let me know if that works.

Note that for now, if you launch with the SMART launcher it won't work because it will use that proxy. To try with an open server do
```js
const client = FHIR.client("https://r4.smarthealthit.org");

client.patch("Encounter/cb41d6f8-3441-4483-8236-e457c549f793", [
    { op: "replace", path: "/period/end", value: new Date().toISOString() }
]).then(console.log, console.error);
```

**Comment by thuann-vn** [comment] 2021-06-11 10:01
@vlad-ignatov thank you for your support. I tested and it's working now. You saved my day! 👯

**Closed** 2021-07-21 05:21 UTC

**Comment by MrSerWin** [comment] 2022-01-13 14:40
this problem is still actual for me. I'm using the latest version from CDN 
https://cdn.jsdelivr.net/npm/fhirclient@latest/build/fhir-client.min.js
My request is : 
const url = /Patient/PatientID; // I use correct ID patient there
const response = await fhirClient.patch(url, body)
where body is:```
 [
    {
        "op": "add",
        "path": "/gender",
        "value": "male"
    },
    {
        "op": "add",
        "path": "/name",
        "value": [
            {
                "family": "Abbott1",
                "given": [
                    "Geoffrey1"
                ]
            }
        ]
    },
    {
        "op": "add",
        "path": "/birthDate",
        "value": "1990-09-01"
    }
]
```

response is: 
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: java.lang.NullPointerException: input cannot be null</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Failed to call access method: java.lang.NullPointerException: input cannot be null"
        }
    ]
}
```
