### ISSUE TITLE
Uncaught (in promise) Error: Failed to fetch the conformance statement from "https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/metadata". TypeError: Network request failed

### ISSUE THREAD

**Issue by msohaib308** [smart-on-fhir/client-js#167] opened 2023-03-31 07:47 UTC
I am having XML response issue

fhirClient is expecting JSON format but fhir server is returning XML
here is the fhir server URLs

https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/metadata
https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/.well-known/smart-configuration

Fhir server provide extra query parameter "_format=json" to get JSON response, this option is only for metadata
but they did not provide this option for "smart-configuration" end point

I don't know how to set this ("_format=json" ) configuration in fhirCLient Library.

https://staging-fhir.ecwcloud.com/fhir/r4/FFBJCD/metadata?_format=json

![Screenshot 2023-03-31 124304](https://user-images.githubusercontent.com/42337255/229057470-3b88fd31-b72c-455b-84ab-75f9ae1a2146.png)

Is there any option to accept XML responses

**Comment by vlad-ignatov** [comment] 2023-03-31 15:09
The client does NOT support XML but it sends and `accept: application/json` header on each request to tell the server how to respond. This seems to work fine with your server.

As the screenshot shows, the problem is not there. You just need to configure / modify your FHIR server to support CORS.

**Comment by msohaib308** [comment] 2023-04-01 05:31
Anyway if i can handle on client side 
Because FHIR server is owned by third party

**Comment by vlad-ignatov** [comment] 2023-04-01 14:36
If you try loading those URLs in a browser window you will get back XML. That is because browsers send some accept headers by default. Otherwise you would get JSON, even if you don't send any accept header. Don't let that trick you into thinking that XML is the issue - in this case what you see is not what you get :)

Every FHIR server MUST support CORS. Otherwise it would be unusable (even if you didn't need to authenticate). You can't work around this from the client side and that is exactly the point of CORS - clients should be rejected unless server admins say they shouldn't.

Your only choice is to let them know that CORS must be enabled and perhaps send them that screenshot for reference.

**Comment by zamananjum0** [comment] 2023-09-27 12:47
Is this resolve? 
@msohaib308 Can you please guide me on this?

**Comment by msohaib308** [comment] 2023-09-27 13:00
Issue is not resolved yet
however they suggested to try implementation on backend side 
Below is the email that i got from ECW Team 

![image](https://github.com/smart-on-fhir/client-js/assets/42337255/9d4a0f82-def7-4577-98b7-b59b6c66650a)

**Comment by vincehartman38** [comment] 2024-06-12 21:40
Did the 21st Century Act require SMART on FHIR apps by EHRs for EHR-launch require it to be browser-based? Like is this allowable behavior that eCW can argue CORS whitelisting as an "enhancement request" if @vlad-ignatov is stating it's a requirement for SMART on FHIR to function and push us to do (3). @msohaib308 - how did you end up resolving this?

**Comment by vlad-ignatov** [comment] 2024-08-27 14:47
I see  that they have added CORS now, so this can be closed.

**Closed by vlad-ignatov** 2024-08-27 14:47 UTC
