### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by muzZziii** [smart-on-fhir/client-js#74] opened 2020-02-13 11:48 UTC
I am creating an app with Vue.js,
Apps works fine in IE 11 before i install the package from npm and use in my Vue.js code then i got this error 
![image](https://user-images.githubusercontent.com/27478777/74432169-91f8bf00-4e80-11ea-9a8b-21a11ce295b5.png)

**Comment by vlad-ignatov** [comment] 2020-02-13 15:31
Any chance you can see what the error actually is? Perhaps if you set the debugger to break on exceptions?

**Comment by muzZziii** [comment] 2020-02-14 05:20
Yes the error is in browser.js
![image](https://user-images.githubusercontent.com/27478777/74503698-8d311b00-4f13-11ea-958e-e27dd01e1d8c.png)

**Comment by vlad-ignatov** [comment] 2020-02-15 17:13
It is hard to tell from a screenshot, but I can see a `const` there. There is something wrong with this build. How are you importing the library?

**Comment by chgl** [comment] 2020-02-20 02:01
I've had the same issue. Transpiling these packages did the trick, see my vue.config.js:

```js
module.exports = {
  transpileDependencies: ["fhirpath", "fhirclient", "debug"],
};
```
(In case you plan on using fhirpath as well it has a similar issue).

I'm not familiar enough with the whole Babel thing to know if this may also be possible or more convenient to "fix" upstream.

**Comment by muzZziii** [comment] 2020-02-20 08:12
Its worked in Vue.js as @chgl mentioned Thanks for the help.

**Comment by muzZziii** [comment] 2020-02-21 06:57
I have imported fhirclient in my auth.js file and compile with webpack and babel and got the error, 
(I haven't worked with babel and webpack before so struggling from two days)
![image](https://user-images.githubusercontent.com/27478777/75011325-2b3b5d00-54a1-11ea-80ab-da932c1e9d15.png)

**Comment by vlad-ignatov** [comment] 2020-02-22 16:41
I can confirm that `debug` is problematic because it ships un-transpiled ES6 code. It is a common pattern in Webpack loaders to skip the entire node_modules folder, but if you use `debug` that doesn't work. It needs to be configured explicitly. For example https://github.com/smart-on-fhir/client-js/blob/master/webpack.config.js#L126-L129

However, I still think that this shouldn't happen the way it did for you. It is either a matter of proper Webpack or Babel configuration, or wrong usage. Can you provide a snippet of you `import` or `require` statements and maybe a `webpack.config`?

**Comment by muzZziii** [comment] 2020-02-24 06:02
here is my babe.config.json
![image](https://user-images.githubusercontent.com/27478777/75131106-41d8f280-56f3-11ea-978b-90d45b7e16b0.png)

and webpack.json

![image](https://user-images.githubusercontent.com/27478777/75131486-1ce57f00-56f5-11ea-9e78-71ffdda73154.png)

**Comment by bhinebaugh** [comment] 2020-03-04 17:05
I'm not able to reproduce that error when testing with a basic Vue app generated via the [Vue CLI](https://cli.vuejs.org). Importing `fhirclient` and building the app yields no untranspiled code in the resulting .js files for me.

Nothing looks particularly out of place in your Babel and Webpack configuration. Since you mentioned you are new to using them, can I ask how are you importing `fhirclient` in your auth.js? (by name or via path is going to make a difference in how npm and Babel are involved)

**Comment by SvetlozarValchev** [comment] 2020-03-23 19:29
![image](https://user-images.githubusercontent.com/446056/77355517-3eb24000-6d4d-11ea-9a82-fabc1de9aa92.png)

Same problem, I'm getting this, which takes me here:

![image](https://user-images.githubusercontent.com/446056/77355579-5a1d4b00-6d4d-11ea-9e71-097cf085a861.png)

**Comment by SvetlozarValchev** [comment] 2020-03-23 21:28
Yup, only way to fix this at the moment is to include the barebones build/fhir-client.js directly as a script tag `<script src="..."></script>`. If you include it in your project, you'll get `Error: Out of stack space`, if you include it normally as a module `import {oauth2 as SMART} from "fhirclient"` you'll get `expected identifier` which is because the code didn't transpile.

#How to reproduce:

1. Get [aurelia-cli](https://github.com/aurelia/cli)
2. Type `au new`
3. Enter project name
4. Select `Default TypeScript App`
5. Select `Yes, use NPM`
6. Get in the aurelia directory
7. Install fhirclient `npm install fhirclient`
8. Open `src/app.ts`
9. Add at the top of the file: `import {oauth2 as SMART} from "fhirclient"`
10. Add method attached with authorize call and params, the app.ts should look like this:

```import {oauth2 as SMART} from "fhirclient"

export class App {
  public message: string = 'Hello World!';

  attached() {
    SMART.authorize({
      client_id: "carein",
      scope: "launch/encounter launch/patient fhirUser openid patient/*.read",
      iss: "http://207.180.250.172:8100",
    });
  }
}
```

11. Type `au run` and 
12. open `http://127.0.0.1:8080/` in Internet Explorer 11
13. Observe error `Possible Unhandled Promise Rejection: SyntaxError: Expected identifier`

**Comment by pgross41** [comment] 2020-04-03 21:47
I also have this issue, it's because of the destructured assignment from `getSmartApi` on Line 7 in `browser.js`: 
```js
const adapter = new BrowserAdapter_1.default();
const {
  ready,
  authorize,
  init,
  client,
  options
} = adapter.getSmartApi();
```

In my bundle it looks like this:
```js
const r=new(n(257).default),{ready:i,authorize:o,init:a,client:s,options:u}=r.getSmartApi();
```

A minimal example to recreate the issue in the IE console is this: 
```js
const {test} = {test: 1}
```
---

My application uses destructured assignments and it is transpiled away just fine:

**In**
```js
const { firstName, lastName } = parseNames(fhirUser);
```

**Out**
```js
  (u = (0, a.parseNames)(o)),
  (c = u.firstName),
  (l = u.lastName)
```

I can't figure out how to make it transpile it out of fhirclient 🙁

**Comment by pgross41** [comment] 2020-04-06 03:55
Looks like I'm able to `import 'fhirclient/build/fhir-client'` as a workaround but it makes `FHIR` global and adds 167 KB to the bundle (compared to importing the module).

**Comment by SvetlozarValchev** [comment] 2020-05-20 14:06
Is this going to be fixed?

**Comment by vlad-ignatov** [comment] 2020-09-25 17:47
Importing `fhirclient/build/fhir-client` works. That is the same as including it via script tag, which might be even better as the bundler will not even have to deal with `import 'fhirclient/build/fhir-client'` statements...

Anyway, I had not used Aurelia before so I had to mess around. It looks like I found a solution, although I'm not sure if it is the best one. Perhaps there is a better way to configure Aurelia to do this? Here is what I found:

The `fhirclient` library ships two folders:
- `build` - contains browser bundles
- `lib` - contains ES6 files

When used as a module (in node or through a bundler), the `lib` folder should be used.

Initially I though that Aurelia is not properly following the "browser" key from fhirclient's package.json because there are such complaints online. However, this is probably fixed now and even if I  import `"fhirclient/lib/entry/browser"`, I still have the same issue.

With vanilla TS projects, if `allowJs` is set in tsconfig.json, JS files are also managed with TSC. This does not seem to be the case with Aurelia. To fix that I used the following (somewhat brute-force) approach:

In webpack.config.js:
```js
// Replace the following line:
{ test: /\.ts$/, loader: "ts-loader" },
// with this:
{ test: /\.[jt]s$/, loader: "ts-loader", include: [ srcDir, path.join(__dirname, "node_modules/fhirclient") ]},
```

**Comment by SvetlozarValchev** [comment] 2020-09-25 19:01
We moved to Vue and are importing it like this - `import "fhirclient/build/fhir-client"` and using FHIR as part of the global (window) object. It works without an issue in IE11 so far.

**Comment by vlad-ignatov** [comment] 2020-10-05 16:07
Great! Despite the title, this is not an issue with IE, but with different build systems. So far we have identified how to avoid it in Aurelia and Vue. I will close this now and "expect" it to be re-opened for other build systems.

**Closed by vlad-ignatov** 2020-10-05 16:07 UTC

**Comment by pgross41** [comment] 2021-01-12 19:15
I found how to make IE work with webpack. It's very common for configs to have babel ignore node_modules, example: 

```js
module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    }
}
```

Explicitly adding the fhir client as a separate rule will cause babel to transpile the code despite the node_modules exclusion. 
```js
module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    },
    {
      test: /fhirclient/,
      loader: 'babel-loader'
    },
  ]
},
```

Modules in /lib for browser apps are typically pre-transpiled to ES5. Removing the [node 10 target](https://github.com/smart-on-fhir/client-js/blob/master/babel.config.js#L34) does make it work in IE. I realize this client can be used as a Node library as well as a browser library though. My main concern is bundle size. These are the sizes I saw for my project:

Today: 
* Using the prebuilt browser version with global FHIR: **1,521 KB**

Compared to... 
* Importing the node modules as-is (no IE support): **1,347 KB** (-174)
* Compiling client-js with no target in babel config (you transpile it): **1,432 KB** (-89)
* Use babel-loader in webpack config (I transpile it): **1,364 KB** (-157)

Based on those numbers I propose you change nothing and I will transpile it downstream in my project 😊 however, it might be helpful to put this info somewhere in the documentation.
